spring:
  application:
    name: task-manager-demo
  profiles:
    active: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/taskmanager_demo
    username: ${DB_USERNAME:taskmanager}
    password: ${DB_PASSWORD:taskmanager}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    baseline-version: 1

  security:
    jwt:
      secret: ${JWT_SECRET:demo-secret-key-change-in-production-minimum-32-characters}
      expiration: ${JWT_EXPIRATION:86400000} # 24 hours in milliseconds
      refresh-expiration: ${JWT_REFRESH_EXPIRATION:604800000} # 7 days

  cache:
    type: simple
    cache-names:
      - users
      - tasks
      - projects

server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /api
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param
    include-exception: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when_authorized
  info:
    env:
      enabled: true

logging:
  level:
    com.demo.copilot.taskmanager: INFO
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} %5p ${PID:- } --- [%t] %-40.40logger{39} : %m%n%wEx"
  file:
    name: logs/task-manager.log

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
  info:
    title: Task Manager API
    description: Clean Architecture Demo for GitHub Copilot
    version: 1.0.0
    contact:
      name: Demo Team
      email: demo@example.com

# Application specific configurations
app:
  security:
    cors:
      allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:3001}
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
      allowed-headers: "*"
      allow-credentials: true
      max-age: 3600
  
  file-upload:
    max-size: ${FILE_UPLOAD_MAX_SIZE:10485760} # 10MB
    allowed-types: ${FILE_UPLOAD_ALLOWED_TYPES:jpg,jpeg,png,gif,pdf,doc,docx,txt,xlsx}
    storage-path: ${FILE_UPLOAD_PATH:./uploads}
  
  pagination:
    default-page-size: 20
    max-page-size: 100

---
spring:
  config:
    activate:
      on-profile: dev
      
logging:
  level:
    com.demo.copilot.taskmanager: DEBUG
    org.springframework.web: DEBUG

---
spring:
  config:
    activate:
      on-profile: test
      
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
    
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
    
  flyway:
    enabled: false

logging:
  level:
    org.springframework.web: INFO
    org.hibernate: INFO

---
spring:
  config:
    activate:
      on-profile: prod
      
  jpa:
    show-sql: false
    
logging:
  level:
    com.demo.copilot.taskmanager: WARN
    org.springframework.security: WARN
    org.hibernate: WARN
  file:
    name: /var/log/task-manager/application.log